### ISSUE TITLE
Return to main screen file not found.

### ISSUE THREAD

**Issue by myerssr** [yousefaltufiel/Elemental#2]
Referring to test case 2, TReturnMainScreen, while viewing the Elements List page and clicking on 'Return to the Main Element Screen...', the error of 'File Not Found' populates the next page.

Steps to reproduce: Start within the Elements List page and click on the Return to the Main Element Screen link in blue on the bottom of the page.

Expected Result: Upon clicking on the link, the main page titled 'Welcome to Elemental!' should be displayed.

**Comment by yousefaltufiel** [comment]
the error was in the coding when you return to the main element screen it should take you back to main screen. what i found is a spelling error with the code "indxe.html" so i correct it to "index.html" and i retest the test case TReturnMainScreen and it works fine after that.

**Comment by myerssr** [comment]
Re-attempted test case TReturnMainScreen was successful.
