### ISSUE TITLE
page not found error when try to return to main element list

### ISSUE THREAD

**Issue by yousefaltufiel** [yousefaltufiel/Elemental#3]
while viewing Air i clicked 'Return to the Elements List...' and then the page gave me an error.

Expected result: return to the main page.

**Comment by myerssr** [comment]
The HTML code to return to the list was spelled incorrectly and fixed. Test was re-completed with success according to TViewSpecificElement, returning to Element List.

**Comment by yousefaltufiel** [comment]
i test it out again and find out that everything is correct and got fixed.
