### ISSUE TITLE
Page water contains Information about Earth and Earth picture 

### ISSUE THREAD

**Issue by yousefaltufiel** [yousefaltufiel/Elemental#6]
After clicking at page water the page shows picture of Earth and information about Earth 

Expected result: Information and Picture about Water

**Comment by myerssr** [comment]
HTML code was referencing the earth.png file rather than the water.png file. Corrected and test run successful. Also, the title bar was showing Air rather than Water and this was also fixed.

**Comment by yousefaltufiel** [comment]
i did test it out and i found out that everything is correct.
